// Nội dung các bài hướng dẫn AutoCAD (song ngữ vi/en). Sinh HTML bằng: node scripts/build-guides.cjs
// Mỗi khối: [loại, vi, en]. Loại: p, h2, h3, ul (vi/en là mảng <li>), tip (vi/en = [tiêu đề, nội dung]).
const p = (vi, en) => ['p', vi, en];
const h2 = (vi, en) => ['h2', vi, en];
const h3 = (vi, en) => ['h3', vi, en];
const ul = (vi, en) => ['ul', vi, en];
const tip = (vi, en) => ['tip', vi, en];

module.exports = [
  {
    slug: 'lisp-khong-chay-unknown-command-autocad',
    title: 'Lisp Không Chạy, Báo "Unknown Command" Trong AutoCAD: Nguyên Nhân & Cách Sửa',
    titleEn: 'AutoCAD Lisp Not Running or "Unknown Command": Causes & Fixes',
    badge: 'Sửa Lỗi', badgeEn: 'Troubleshooting',
    desc: 'Nạp file .lsp bằng APPLOAD xong nhưng gõ lệnh vẫn báo Unknown command? Danh sách nguyên nhân thường gặp và cách kiểm tra từng bước, từ tên lệnh c: đến cảnh báo bảo mật.',
    descEn: 'Loaded a .lsp file with APPLOAD but the command still says Unknown command? Common causes and a step-by-step checklist.',
    related: ['huong-dan-appload-lisp-autocad', 'tuy-chinh-lenh-autolisp', 'phan-biet-appload-va-netload-trong-autocad'],
    body: [
      p('Bạn tải một file Lisp về, nạp vào AutoCAD, gõ lệnh thì nhận được <code>Unknown command</code>. Đây là lỗi gặp nhiều nhất khi mới dùng Lisp, và gần như luôn rơi vào một trong các nguyên nhân dưới đây. Hãy kiểm tra theo thứ tự.',
        'You download a Lisp file, load it into AutoCAD, type the command and get <code>Unknown command</code>. This is the most common beginner problem and it almost always comes down to one of the causes below. Check them in order.'),

      h2('1. File chưa được nạp thành công', '1. The file was not actually loaded'),
      p('Sau khi chọn file trong hộp thoại <code>APPLOAD</code>, bạn phải bấm <strong>Load</strong> rồi xem dòng thông báo ở cuối hộp thoại và trong Command line. Nếu có chữ <code>loaded successfully</code> hoặc tương tự là file đã nạp. Chỉ chọn file mà chưa bấm Load thì lệnh chưa tồn tại.',
        'After choosing the file in the <code>APPLOAD</code> dialog you must click <strong>Load</strong> and read the message at the bottom of the dialog and in the Command line. Selecting the file without clicking Load does nothing.'),
      p('Xem thêm cách làm đúng tại <a href="/autocad/chiase/huong-dan-appload-lisp-autocad.html">Hướng dẫn APPLOAD &amp; Startup Suite</a>.',
        'See the proper workflow in the <a href="/autocad/chiase/huong-dan-appload-lisp-autocad.html">APPLOAD &amp; Startup Suite guide</a>.'),

      h2('2. Gõ sai tên lệnh', '2. You typed the wrong command name'),
      p('Tên file không phải là tên lệnh. Lệnh được định nghĩa bên trong file, dạng <code>(defun c:TENLENH ()</code>. Mở file <code>.lsp</code> bằng Notepad, tìm các dòng <code>defun c:</code>: phần sau <code>c:</code> chính là lệnh bạn phải gõ. Ví dụ <code>(defun c:MH ()</code> thì gõ <code>MH</code>.',
        'The file name is not the command name. The command is defined inside the file as <code>(defun c:COMMANDNAME ()</code>. Open the <code>.lsp</code> file in Notepad and search for <code>defun c:</code>; the text after <code>c:</code> is what you type. For example <code>(defun c:MH ()</code> means you type <code>MH</code>.'),
      p('Nếu hàm được khai báo <strong>không có</strong> tiền tố <code>c:</code> thì nó chỉ gọi được dưới dạng hàm Lisp có ngoặc, ví dụ <code>(tenham)</code>, chứ không gõ như một lệnh thường.',
        'If the function is declared <strong>without</strong> the <code>c:</code> prefix it can only be called as a Lisp function in parentheses, such as <code>(functionname)</code>, not typed like a normal command.'),
      p('Muốn đổi tên lệnh cho dễ nhớ, xem <a href="/autocad/chiase/tuy-chinh-lenh-autolisp.html">Hướng dẫn tùy chỉnh &amp; đổi tên lệnh AutoLISP</a>.',
        'To rename a command, see <a href="/autocad/chiase/tuy-chinh-lenh-autolisp.html">How to customize AutoLISP command names</a>.'),

      h2('3. File bị chặn bởi cảnh báo bảo mật', '3. The file is blocked by the security setting'),
      p('Các bản AutoCAD mới có cơ chế an toàn cho việc nạp mã. Nếu thư mục chứa file không nằm trong danh sách tin cậy, AutoCAD có thể hiện cảnh báo hoặc từ chối nạp. Cách xử lý chi tiết ở bài <a href="/autocad/chiase/trusted-paths-secureload-autocad.html">TRUSTEDPATHS &amp; SECURELOAD</a>.',
        'Recent AutoCAD versions restrict code loading. If the folder is not in the trusted list, AutoCAD may warn or refuse to load the file. See the <a href="/autocad/chiase/trusted-paths-secureload-autocad.html">TRUSTEDPATHS &amp; SECURELOAD</a> guide for the fix.'),

      h2('4. File bị lỗi cú pháp hoặc lưu sai định dạng', '4. Syntax error or wrong file encoding'),
      ul(['Thiếu hoặc thừa dấu ngoặc: Command line thường hiện dòng báo lỗi bắt đầu bằng <code>; error:</code> ngay khi nạp.',
          'Lưu file bằng Word hoặc trình soạn thảo thêm định dạng: file <code>.lsp</code> phải là văn bản thuần (plain text), nên dùng Notepad.',
          'Đuôi file bị thành <code>.lsp.txt</code> khi tải về: bật hiển thị phần mở rộng trong Windows để kiểm tra và đổi lại tên.'],
         ['Missing or extra parentheses: the Command line usually prints an error starting with <code>; error:</code> as soon as you load.',
          'Saving with Word or a rich editor: a <code>.lsp</code> file must be plain text, so use Notepad.',
          'The extension became <code>.lsp.txt</code> after download: show file extensions in Windows and rename it.']),

      h2('5. Lisp phụ thuộc file khác', '5. The Lisp depends on another file'),
      p('Một số bộ Lisp gọi thêm file khác (hàm dùng chung, file dữ liệu, hộp thoại <code>.dcl</code>). Nếu bạn chỉ copy riêng một file ra khỏi bộ thì lệnh có thể nạp được nhưng chạy báo lỗi. Hãy giữ nguyên cả thư mục như bản gốc và thêm thư mục đó vào đường dẫn tìm kiếm của AutoCAD.',
        'Some Lisp packages call other files (shared functions, data files, <code>.dcl</code> dialogs). If you copy a single file out of the set, the command may load but fail when it runs. Keep the whole folder together and add it to AutoCAD\'s search path.'),

      h2('6. Lisp mất sau khi đóng AutoCAD', '6. The Lisp disappears when AutoCAD restarts'),
      p('Lisp nạp bằng APPLOAD chỉ tồn tại trong phiên làm việc hiện tại. Để tự nạp mỗi lần mở AutoCAD, thêm file vào <strong>Startup Suite</strong> (nút Contents trong hộp thoại APPLOAD).',
        'Lisp loaded with APPLOAD only lasts for the current session. To load it every time AutoCAD starts, add the file to the <strong>Startup Suite</strong> (the Contents button in the APPLOAD dialog).'),

      tip(['Danh sách kiểm tra nhanh', 'Quick checklist'],
          ['Đã bấm Load và thấy thông báo thành công? Đã mở file kiểm tra đúng tên <code>defun c:</code>? Thư mục đã nằm trong vùng tin cậy? Không có dòng <code>; error:</code> khi nạp? Nếu cả bốn đều ổn mà vẫn lỗi, thử mở bản vẽ mới và nạp lại để loại trừ lỗi riêng của bản vẽ.',
           'Did you click Load and see success? Did you check the exact <code>defun c:</code> name? Is the folder trusted? No <code>; error:</code> line on load? If all four are fine and it still fails, try a new drawing and load again to rule out a drawing-specific problem.']),
    ],
  },

  {
    slug: 'trusted-paths-secureload-autocad',
    title: 'Cảnh Báo Bảo Mật Khi Nạp Lisp/DLL Trong AutoCAD: TRUSTEDPATHS & SECURELOAD',
    titleEn: 'Security Warning When Loading Lisp/DLL in AutoCAD: TRUSTEDPATHS & SECURELOAD',
    badge: 'Cài Đặt', badgeEn: 'Settings',
    desc: 'Giải thích biến SECURELOAD và TRUSTEDPATHS, cách thêm thư mục vào vùng tin cậy (Trusted Locations) để nạp Lisp, DLL không bị cảnh báo hoặc chặn.',
    descEn: 'What the SECURELOAD and TRUSTEDPATHS variables do and how to add a folder to Trusted Locations so Lisp and DLL files load without warnings.',
    related: ['huong-dan-appload-lisp-autocad', 'huong-dan-netload-dll-autocad', 'lisp-khong-chay-unknown-command-autocad'],
    body: [
      p('Khi nạp Lisp hoặc DLL từ một thư mục lạ, AutoCAD có thể hiện hộp thoại cảnh báo bảo mật hoặc từ chối nạp. Đó là cơ chế bảo vệ do hai biến hệ thống <code>SECURELOAD</code> và <code>TRUSTEDPATHS</code> điều khiển. Bài này giải thích chúng và cách thiết lập để công cụ của bạn chạy mượt mà mà vẫn an toàn.',
        'When you load Lisp or DLL files from an unfamiliar folder, AutoCAD may show a security warning or refuse to load. This protection is controlled by two system variables, <code>SECURELOAD</code> and <code>TRUSTEDPATHS</code>. This guide explains them and how to configure them safely.'),

      h2('SECURELOAD là gì?', 'What is SECURELOAD?'),
      p('<code>SECURELOAD</code> quyết định AutoCAD xử lý thế nào với file thực thi (Lisp, ARX, DLL...) nằm ngoài vùng tin cậy:',
        '<code>SECURELOAD</code> decides how AutoCAD treats executable files (Lisp, ARX, DLL...) located outside trusted folders:'),
      ul(['<code>0</code>: nạp từ mọi nơi và không cảnh báo (kém an toàn nhất).',
          '<code>1</code>: nạp thẳng từ vùng tin cậy, còn ngoài vùng tin cậy thì hỏi bạn có cho phép không.',
          '<code>2</code>: chỉ nạp từ vùng tin cậy, các nơi khác bị từ chối.'],
         ['<code>0</code>: load from anywhere with no warning (least safe).',
          '<code>1</code>: load directly from trusted folders and prompt you for anything outside them.',
          '<code>2</code>: load only from trusted folders; everything else is refused.']),
      p('Giá trị mặc định có thể khác nhau tùy phiên bản AutoCAD. Gõ <code>SECURELOAD</code> trong Command line để xem giá trị hiện tại trên máy bạn.',
        'The default value can vary by AutoCAD version. Type <code>SECURELOAD</code> in the Command line to see the current value on your machine.'),

      h2('Cách thêm thư mục vào vùng tin cậy', 'How to add a folder to the trusted list'),
      h3('Cách 1: qua hộp thoại Options', 'Method 1: via the Options dialog'),
      ul(['Gõ <code>OP</code> và nhấn Enter để mở Options.',
          'Chọn tab <strong>Files</strong>, mở mục <strong>Trusted Locations</strong>.',
          'Chọn <strong>Add</strong> rồi <strong>Browse</strong> tới thư mục chứa Lisp/DLL của bạn.',
          'Bấm OK. Từ lần nạp sau, file trong thư mục này sẽ không bị cảnh báo.'],
         ['Type <code>OP</code> and press Enter to open Options.',
          'Go to the <strong>Files</strong> tab and expand <strong>Trusted Locations</strong>.',
          'Choose <strong>Add</strong>, then <strong>Browse</strong> to the folder containing your Lisp/DLL files.',
          'Click OK. Files in this folder will no longer trigger a warning.']),
      h3('Cách 2: qua biến TRUSTEDPATHS', 'Method 2: via the TRUSTEDPATHS variable'),
      p('Gõ <code>TRUSTEDPATHS</code> rồi nhập danh sách thư mục, ngăn cách bằng dấu chấm phẩy. Thêm <code>...</code> ở cuối đường dẫn để bao gồm cả thư mục con:',
        'Type <code>TRUSTEDPATHS</code> and enter the folder list, separated by semicolons. Add <code>...</code> at the end of a path to include its subfolders:'),
      p('<code>C:\\Lisp;D:\\CAD Tools\\...</code>', '<code>C:\\Lisp;D:\\CAD Tools\\...</code>'),
      p('Lưu ý: khi nhập biến, nhớ giữ lại các đường dẫn đã có sẵn, nếu không bạn sẽ ghi đè mất chúng.',
        'Note: when you set the variable, keep the paths that are already there, otherwise you will overwrite them.'),

      h2('Nên đặt thư mục nào làm tin cậy?', 'Which folders should be trusted?'),
      ul(['Chỉ thêm thư mục chứa công cụ bạn biết rõ nguồn gốc, ví dụ thư mục cài đặt Lisp/plugin của riêng bạn.',
          'Không thêm cả ổ đĩa (<code>C:\\</code>) hoặc thư mục <code>Downloads</code>, vì file tải về bất kỳ cũng sẽ được tin cậy.',
          'Đừng hạ <code>SECURELOAD</code> xuống 0 chỉ để hết cảnh báo; thêm đúng thư mục vào vùng tin cậy sẽ an toàn hơn.'],
         ['Only add folders holding tools whose source you know, such as your own Lisp or plugin folder.',
          'Do not add a whole drive (<code>C:\\</code>) or your <code>Downloads</code> folder, because any downloaded file would then be trusted.',
          'Do not set <code>SECURELOAD</code> to 0 just to silence the warning; trusting the right folder is safer.']),

      tip(['Với file DLL tải từ Internet', 'For DLL files downloaded from the Internet'],
          ['Ngoài vùng tin cậy, Windows còn có thể đánh dấu file tải về là bị chặn. Hãy bấm chuột phải vào file, chọn Properties và tích <strong>Unblock</strong> trước khi dùng <code>NETLOAD</code>. Chi tiết tại <a href="/autocad/chiase/huong-dan-netload-dll-autocad.html">Hướng dẫn NETLOAD</a>.',
           'Besides trusted folders, Windows may also mark downloaded files as blocked. Right-click the file, open Properties and tick <strong>Unblock</strong> before using <code>NETLOAD</code>. Details in the <a href="/autocad/chiase/huong-dan-netload-dll-autocad.html">NETLOAD guide</a>.']),
    ],
  },

  {
    slug: 'giam-dung-luong-file-dwg-autocad',
    title: 'Cách Giảm Dung Lượng File DWG Nặng Và Làm AutoCAD Chạy Nhanh Hơn',
    titleEn: 'How to Reduce a Heavy DWG File Size and Speed Up AutoCAD',
    badge: 'Mẹo Hiệu Suất', badgeEn: 'Performance Tips',
    desc: 'Các bước dọn file DWG nặng, chậm: PURGE, AUDIT, OVERKILL, WBLOCK sang file mới, xử lý Xref, ảnh và block thừa. Làm đúng thứ tự để giảm dung lượng an toàn.',
    descEn: 'Steps to clean up a heavy, slow DWG: PURGE, AUDIT, OVERKILL, WBLOCK to a new file, handling Xrefs, images and unused blocks.',
    related: ['huong-dan-lenh-layiso-autocad', 'huong-dan-appload-lisp-autocad', 'tuy-chinh-lenh-autolisp'],
    body: [
      p('File DWG nặng làm AutoCAD mở lâu, zoom giật và dễ treo. Nguyên nhân thường không phải do bản vẽ "to" mà do dữ liệu thừa tích lũy qua thời gian: block, layer, style không dùng, đối tượng trùng lặp, dữ liệu lỗi. Dưới đây là quy trình dọn theo thứ tự nên làm.',
        'A heavy DWG makes AutoCAD slow to open, laggy when zooming and prone to crashing. The cause is usually not the drawing size itself but leftover data that builds up over time: unused blocks, layers and styles, duplicate objects, corrupted data. Here is a cleanup routine in a sensible order.'),
      tip(['Làm trước khi dọn', 'Before you clean'],
          ['Luôn lưu một bản sao của file gốc trước khi dọn. Một số bước (đặc biệt là PURGE tất cả và OVERKILL) xóa dữ liệu mà bạn không thể hoàn tác sau khi đã lưu.',
           'Always save a copy of the original file first. Some steps (especially purging everything and OVERKILL) remove data that cannot be undone after you save.']),

      h2('Bước 1: PURGE các đối tượng không dùng', 'Step 1: PURGE unused objects'),
      p('Gõ <code>PURGE</code> (hoặc <code>PU</code>), chọn các nhóm cần dọn như block, layer, linetype, text style, dimension style rồi bấm Purge All. Lệnh này xóa các định nghĩa không còn được sử dụng. Có thể cần chạy lặp lại 2 đến 3 lần vì xóa xong nhóm này lại làm lộ ra nhóm khác chưa dùng.',
        'Type <code>PURGE</code> (or <code>PU</code>), select the groups to clean, such as blocks, layers, linetypes, text styles and dimension styles, then click Purge All. It removes definitions that are no longer used. You may need to run it two or three times because removing one group exposes others that are now unused.'),

      h2('Bước 2: AUDIT để sửa lỗi dữ liệu', 'Step 2: AUDIT to fix data errors'),
      p('Gõ <code>AUDIT</code> và chọn <strong>Yes</strong> để sửa lỗi phát hiện được. Dữ liệu lỗi có thể làm file phình to hoặc chạy chậm bất thường. Nếu file không mở được, thử lệnh <code>RECOVER</code> thay cho mở thông thường.',
        'Type <code>AUDIT</code> and choose <strong>Yes</strong> to fix any errors found. Corrupted data can bloat a file or slow it down. If the file will not open, try <code>RECOVER</code> instead of a normal open.'),

      h2('Bước 3: OVERKILL xóa đối tượng trùng', 'Step 3: OVERKILL to remove duplicates'),
      p('Gõ <code>OVERKILL</code>, chọn toàn bộ bản vẽ. Lệnh sẽ xóa các đối tượng trùng nhau hoặc chồng lên nhau (đường line, arc, polyline vẽ đè cùng vị trí). Bản vẽ nhập từ nhiều nguồn hoặc copy nhiều lần thường có rất nhiều đối tượng loại này. Nên xem lại hộp thoại tùy chọn trước khi chạy để không gộp những thứ bạn muốn giữ.',
        'Type <code>OVERKILL</code> and select the whole drawing. It deletes duplicate or overlapping objects (lines, arcs and polylines drawn on top of each other). Drawings merged from several sources or copied many times often contain plenty of these. Review the options dialog first so you do not merge things you want to keep.'),

      h2('Bước 4: Kiểm tra Xref, ảnh và đối tượng tham chiếu', 'Step 4: Check Xrefs, images and references'),
      ul(['Mở <code>XREF</code> (Xref Manager) để gỡ bỏ Xref không dùng, tránh Xref bị mất đường dẫn.',
          'Với ảnh nền (raster) lớn, cân nhắc giảm kích thước ảnh hoặc dùng đường dẫn tương đối.',
          'Hạn chế chèn bản vẽ khác bằng <code>INSERT</code> nguyên cả file vì kéo theo toàn bộ dữ liệu của file đó; dùng <code>WBLOCK</code> để chỉ xuất phần cần thiết.'],
         ['Open <code>XREF</code> (Xref Manager) and detach unused Xrefs, and avoid Xrefs with broken paths.',
          'For large raster images, consider shrinking them or using relative paths.',
          'Avoid inserting whole drawings with <code>INSERT</code>, since all of that file\'s data comes along; use <code>WBLOCK</code> to export only what you need.']),

      h2('Bước 5: WBLOCK sang file mới', 'Step 5: WBLOCK into a fresh file'),
      p('Đây là cách hiệu quả khi các bước trên chưa đủ. Gõ <code>WBLOCK</code>, chọn <strong>Objects</strong> hoặc toàn bộ đối tượng cần giữ, đặt tên file mới và lưu. File mới chỉ chứa phần bạn chọn nên thường nhẹ hơn rõ rệt so với bản gốc đã tích lũy dữ liệu thừa. Kiểm tra lại layer, style và layout trong file mới trước khi thay thế file cũ.',
        'This helps when the steps above are not enough. Type <code>WBLOCK</code>, select <strong>Objects</strong> (or everything you want to keep), name the new file and save. The new file contains only what you selected, so it is often noticeably lighter than the original that accumulated leftover data. Check layers, styles and layouts in the new file before replacing the old one.'),

      h2('Mẹo giữ file nhẹ về lâu dài', 'Habits that keep files light'),
      ul(['Dọn PURGE định kỳ, không chờ đến lúc file nặng mới làm.',
          'Tránh copy bản vẽ từ các file cũ chứa nhiều rác sang bản vẽ mới bằng Ctrl+C; hãy dọn nguồn trước.',
          'Dùng layer hợp lý, không tạo hàng trăm layer thừa từ bản vẽ nhập về.',
          'Nên dùng <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">LAYISO</a> để cô lập layer khi thao tác, giúp làm việc trên bản vẽ lớn dễ hơn.'],
         ['Run PURGE regularly instead of waiting until the file is heavy.',
          'Avoid copying from old, cluttered drawings into new ones with Ctrl+C; clean the source first.',
          'Use layers sensibly and do not import hundreds of unused layers.',
          'Use <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">LAYISO</a> to isolate layers while working, which makes large drawings easier to handle.']),
    ],
  },

  {
    slug: 'loi-netload-autocad-khong-nap-duoc-dll',
    title: 'Các Lỗi NETLOAD Thường Gặp Trong AutoCAD: Không Nạp Được File DLL',
    titleEn: 'Common NETLOAD Errors in AutoCAD: Unable to Load a DLL',
    badge: 'Sửa Lỗi', badgeEn: 'Troubleshooting',
    desc: 'Tổng hợp các lỗi khi NETLOAD plugin .DLL: FileLoadException 0x80131515, BadImageFormatException, thiếu DLL phụ thuộc, sai phiên bản .NET và file bị khóa. Cách nhận biết và sửa từng lỗi.',
    descEn: 'The usual errors when running NETLOAD on a .DLL plugin: FileLoadException 0x80131515, BadImageFormatException, missing dependencies, .NET version mismatch and locked files.',
    related: ['huong-dan-netload-dll-autocad', 'trusted-paths-secureload-autocad', 'phan-biet-appload-va-netload-trong-autocad'],
    body: [
      p('Khi dùng <code>NETLOAD</code> nạp plugin <code>.DLL</code>, AutoCAD thường chỉ báo một dòng lỗi dài và khó hiểu. Thực ra phần lớn lỗi thuộc vài nhóm quen thuộc. Hãy đọc kỹ nội dung thông báo ở Command line rồi đối chiếu với các mục dưới đây. Nếu bạn chưa biết cách nạp đúng, xem trước <a href="/autocad/chiase/huong-dan-netload-dll-autocad.html">Hướng dẫn NETLOAD</a>.',
        'When you run <code>NETLOAD</code> on a <code>.DLL</code> plugin, AutoCAD often prints a single long, cryptic error. Most failures fall into a few familiar groups. Read the message in the Command line carefully and match it against the sections below. If you are new to the command, start with the <a href="/autocad/chiase/huong-dan-netload-dll-autocad.html">NETLOAD guide</a>.'),

      h2('1. "Could not load file or assembly... Operation is not supported (0x80131515)"', '1. "Could not load file or assembly... Operation is not supported (0x80131515)"'),
      p('Đây là lỗi hay gặp nhất với file tải từ Internet hoặc nhận qua email/chat. Windows đánh dấu file là "đến từ máy tính khác" và .NET từ chối nạp nó.',
        'This is the most common error with files downloaded from the Internet or received by email or chat. Windows marks the file as coming from another computer and .NET refuses to load it.'),
      ul(['Đóng AutoCAD, bấm chuột phải vào file <code>.DLL</code> chọn <strong>Properties</strong>.',
          'Ở tab General, tích ô <strong>Unblock</strong> rồi bấm OK.',
          'Nếu plugin có nhiều DLL, hãy Unblock từng file, hoặc giải nén lại từ file ZIP đã được Unblock trước khi giải nén.',
          'Mở lại AutoCAD và NETLOAD lại.'],
         ['Close AutoCAD, right-click the <code>.DLL</code> file and choose <strong>Properties</strong>.',
          'On the General tab tick <strong>Unblock</strong> and click OK.',
          'If the plugin has several DLLs, unblock each one, or unblock the ZIP before extracting it.',
          'Reopen AutoCAD and run NETLOAD again.']),

      h2('2. BadImageFormatException: "incorrect format"', '2. BadImageFormatException: "incorrect format"'),
      p('Thông báo kiểu <code>An attempt was made to load a program with an incorrect format</code> nghĩa là file DLL không tương thích với AutoCAD đang chạy. Hai nguyên nhân thường gặp:',
        'A message like <code>An attempt was made to load a program with an incorrect format</code> means the DLL is not compatible with the running AutoCAD. Two usual causes:'),
      ul(['<strong>Sai phiên bản .NET:</strong> plugin viết cho .NET Framework (AutoCAD 2024 trở về trước) không nạp được vào AutoCAD dùng .NET mới (AutoCAD 2025 trở đi dùng .NET 8), và ngược lại. Cần bản plugin build đúng cho phiên bản AutoCAD của bạn.',
          '<strong>Sai kiến trúc:</strong> AutoCAD là ứng dụng 64-bit, nên DLL build riêng cho 32-bit (x86) sẽ không nạp được. Plugin cần build ở chế độ x64 hoặc Any CPU.'],
         ['<strong>.NET version mismatch:</strong> a plugin written for .NET Framework (AutoCAD 2024 and earlier) will not load in AutoCAD that runs modern .NET (AutoCAD 2025 onward uses .NET 8), and the reverse. You need a build made for your AutoCAD version.',
          '<strong>Architecture mismatch:</strong> AutoCAD is a 64-bit application, so a DLL built only for 32-bit (x86) will not load. The plugin must be built as x64 or Any CPU.']),
      p('Cách xử lý: tải đúng bản plugin cho phiên bản AutoCAD của bạn, hoặc liên hệ tác giả để xin bản build phù hợp.',
        'Fix: download the build that matches your AutoCAD version, or ask the author for one.'),

      h2('3. "...or one of its dependencies. The system cannot find the file specified"', '3. "...or one of its dependencies. The system cannot find the file specified"'),
      p('Plugin cần thêm một DLL khác (thư viện đi kèm) nhưng không tìm thấy. Thường do bạn chỉ copy riêng một file DLL ra khỏi thư mục gốc.',
        'The plugin needs another DLL (a companion library) and cannot find it, usually because only one DLL was copied out of the original folder.'),
      ul(['Giữ nguyên toàn bộ thư mục plugin như bản phát hành, không tách file.',
          'Đảm bảo các DLL phụ nằm cùng thư mục với file bạn NETLOAD.',
          'Một số plugin cần cài sẵn thành phần như .NET Desktop Runtime hoặc Visual C++ Redistributable; đọc tài liệu đi kèm.'],
         ['Keep the whole plugin folder as released and do not split the files.',
          'Make sure companion DLLs sit in the same folder as the file you NETLOAD.',
          'Some plugins need a runtime such as the .NET Desktop Runtime or the Visual C++ Redistributable; read the bundled documentation.']),

      h2('4. Nạp xong nhưng không thấy lệnh', '4. Loaded, but the command is not found'),
      p('NETLOAD nạp thành công không đồng nghĩa lệnh có sẵn dưới tên bạn đoán. Tên lệnh do tác giả đặt trong mã. Hãy xem tài liệu của plugin để biết đúng tên. Nếu vẫn báo <code>Unknown command</code>, xem thêm <a href="/autocad/chiase/lisp-khong-chay-unknown-command-autocad.html">bài về lỗi Unknown command</a>.',
        'A successful NETLOAD does not mean the command exists under the name you guessed. The author defines command names in code, so check the plugin documentation. If you still get <code>Unknown command</code>, see the <a href="/autocad/chiase/lisp-khong-chay-unknown-command-autocad.html">Unknown command guide</a>.'),

      h2('5. Cảnh báo bảo mật hoặc bị từ chối nạp', '5. Security warning or load refused'),
      p('Nếu thư mục chứa DLL không nằm trong vùng tin cậy, AutoCAD có thể hỏi xác nhận hoặc từ chối hẳn tùy giá trị <code>SECURELOAD</code>. Thêm thư mục vào Trusted Locations theo bài <a href="/autocad/chiase/trusted-paths-secureload-autocad.html">TRUSTEDPATHS &amp; SECURELOAD</a>.',
        'If the DLL folder is not trusted, AutoCAD may ask for confirmation or refuse outright depending on <code>SECURELOAD</code>. Add the folder to Trusted Locations as described in the <a href="/autocad/chiase/trusted-paths-secureload-autocad.html">TRUSTEDPATHS &amp; SECURELOAD</a> guide.'),

      h2('6. Không thay được file DLL mới (file đang bị khóa)', '6. You cannot replace the DLL (file is locked)'),
      p('Sau khi NETLOAD, file DLL bị AutoCAD giữ cho đến khi thoát chương trình, và AutoCAD không có lệnh gỡ nạp. Khi cập nhật plugin hay đang thử bản build mới, Windows sẽ báo file đang được sử dụng. Hãy đóng hẳn AutoCAD (kiểm tra cả Task Manager nếu cần), chép đè file rồi mở lại.',
        'After NETLOAD the DLL stays locked by AutoCAD until you quit, and there is no command to unload it. When updating a plugin or testing a new build, Windows will report the file is in use. Close AutoCAD completely (check Task Manager if needed), overwrite the file and reopen.'),

      h2('7. Mẹo tránh lỗi về sau', '7. Tips to avoid problems'),
      ul(['Đặt plugin ở thư mục cục bộ ổn định, ví dụ <code>C:\\CAD Tools\\TenPlugin</code>, thay vì thư mục Downloads hoặc ổ mạng.',
          'Thêm thư mục đó vào Trusted Locations và (nếu cần) vào Startup Suite để tự nạp khi mở AutoCAD.',
          'Ghi lại nguyên văn thông báo lỗi trước khi hỏi tác giả; dòng chứa tên Exception thường đủ để họ xác định nguyên nhân.'],
         ['Keep plugins in a stable local folder, for example <code>C:\\CAD Tools\\PluginName</code>, rather than Downloads or a network drive.',
          'Add that folder to Trusted Locations and, if needed, load it automatically at startup.',
          'Copy the exact error text before asking the author; the line naming the Exception is usually enough to pinpoint the cause.']),

      tip(['Tóm tắt nhanh', 'Quick summary'],
          ['Operation is not supported (0x80131515): hãy Unblock. Incorrect format: sai bản .NET hoặc sai kiến trúc. Dependencies: thiếu DLL đi kèm. Không thấy lệnh: kiểm tra tên lệnh. File bị khóa: đóng AutoCAD.',
           'Operation is not supported (0x80131515): unblock the file. Incorrect format: wrong .NET version or architecture. Dependencies: a companion DLL is missing. Command not found: check the command name. File locked: close AutoCAD.']),
    ],
  },

  {
    slug: 'phan-biet-layiso-layoff-layfrz-laylck-autocad',
    title: 'Phân Biệt LAYISO, LAYOFF, LAYFRZ, LAYLCK, LAYWALK Trong AutoCAD: Khi Nào Dùng Lệnh Nào?',
    titleEn: 'LAYISO vs LAYOFF, LAYFRZ, LAYLCK and LAYWALK in AutoCAD: Which One to Use?',
    badge: 'So Sánh', badgeEn: 'Comparison',
    desc: 'Bảng so sánh các lệnh quản lý layer theo đối tượng: LAYISO, LAYOFF, LAYFRZ, LAYLCK, LAYWALK. Khác nhau giữa tắt, đóng băng và khóa layer, cách khôi phục và mẹo chọn lệnh nhanh.',
    descEn: 'Comparison of the object-based layer commands LAYISO, LAYOFF, LAYFRZ, LAYLCK and LAYWALK: off vs freeze vs lock, how to restore, and how to choose.',
    related: ['huong-dan-lenh-layiso-autocad', 'giam-dung-luong-file-dwg-autocad', 'huong-dan-appload-lisp-autocad'],
    body: [
      p('Trong AutoCAD, bạn có thể quản lý layer mà không cần mở bảng Layer Properties: chỉ cần chọn một đối tượng rồi dùng các lệnh <code>LAY...</code>. Nhưng có khá nhiều lệnh na ná nhau, dễ nhầm. Bài này so sánh các lệnh hay dùng nhất để bạn chọn đúng lệnh cho từng việc. Nếu muốn đi sâu riêng lệnh LAYISO, xem <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">Hướng dẫn toàn tập về lệnh LAYISO</a>.',
        'In AutoCAD you can manage layers without opening the Layer Properties palette: pick an object and use the <code>LAY...</code> commands. There are several similar-looking commands that are easy to mix up. This guide compares the most useful ones so you pick the right command for each job. For a deep dive on LAYISO itself, see the <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">complete LAYISO guide</a>.'),

      h2('Bảng so sánh nhanh', 'Quick comparison'),
      p('Tất cả lệnh dưới đây tác động lên layer của đối tượng bạn chọn:',
        'All of the commands below act on the layer of the object you select:'),
      ul(['<code>LAYISO</code>: giữ layer của đối tượng được chọn, xử lý (tắt hoặc khóa và làm mờ) mọi layer còn lại. Hoàn tác bằng <code>LAYUNISO</code>.',
          '<code>LAYOFF</code>: tắt layer của đối tượng được chọn. Bật lại tất cả bằng <code>LAYON</code>.',
          '<code>LAYFRZ</code>: đóng băng (Freeze) layer của đối tượng được chọn. Rã băng tất cả bằng <code>LAYTHW</code>.',
          '<code>LAYLCK</code>: khóa layer của đối tượng được chọn. Mở khóa bằng <code>LAYULK</code>.',
          '<code>LAYWALK</code>: mở hộp thoại duyệt từng layer, chỉ hiện layer bạn chọn; khi thoát có thể khôi phục trạng thái ban đầu.'],
         ['<code>LAYISO</code>: keeps the layer of the selected objects and handles (turns off, or locks and fades) every other layer. Undo with <code>LAYUNISO</code>.',
          '<code>LAYOFF</code>: turns off the layer of the selected object. Turn everything back on with <code>LAYON</code>.',
          '<code>LAYFRZ</code>: freezes the layer of the selected object. Thaw everything with <code>LAYTHW</code>.',
          '<code>LAYLCK</code>: locks the layer of the selected object. Unlock with <code>LAYULK</code>.',
          '<code>LAYWALK</code>: opens a dialog to step through layers, showing only the ones you pick; on exit you can restore the original state.']),

      h2('Tắt (Off), đóng băng (Freeze) và khóa (Lock) khác nhau thế nào?', 'Off vs Freeze vs Lock: what is the difference?'),
      ul(['<strong>Off:</strong> đối tượng ẩn khỏi màn hình và không in, nhưng vẫn nằm trong bộ nhớ và vẫn được tính khi tái tạo bản vẽ (regen). Phù hợp để ẩn tạm.',
          '<strong>Freeze:</strong> đối tượng ẩn và không được tính khi regen, nên có thể giúp bản vẽ lớn phản hồi nhanh hơn. Không thể đóng băng layer đang hiện hành.',
          '<strong>Lock:</strong> đối tượng vẫn hiện (có thể làm mờ) nhưng không chọn hoặc sửa được. Phù hợp khi muốn giữ làm nền tham chiếu mà không lỡ tay di chuyển.'],
         ['<strong>Off:</strong> objects are hidden and not plotted but stay in memory and are still processed during a regen. Good for temporarily hiding things.',
          '<strong>Freeze:</strong> objects are hidden and skipped during a regen, which can make large drawings respond faster. You cannot freeze the current layer.',
          '<strong>Lock:</strong> objects stay visible (and can be faded) but cannot be selected or edited. Good for keeping a reference backdrop without moving it by accident.']),

      h2('Khi nào dùng lệnh nào?', 'Which command for which situation?'),
      h3('Muốn chỉ làm việc với một nhóm đối tượng', 'You want to work on one group of objects only'),
      p('Dùng <code>LAYISO</code>, chọn đối tượng cần giữ. Với tùy chọn khóa và làm mờ, các layer còn lại vẫn thấy mờ để bạn định hướng, nhưng không bị sửa nhầm. Xong việc gõ <code>LAYUNISO</code> để trả lại trạng thái cũ.',
        'Use <code>LAYISO</code> and select the objects to keep. With the lock-and-fade option the remaining layers stay faintly visible for orientation but cannot be edited by mistake. When finished, type <code>LAYUNISO</code> to restore the previous state.'),
      h3('Muốn ẩn một vài layer vướng mắt', 'You want to hide a few distracting layers'),
      p('Dùng <code>LAYOFF</code> và chọn từng đối tượng đại diện. Cách này nhanh hơn việc dò tên layer trong danh sách. Khi cần hiện lại, gõ <code>LAYON</code>.',
        'Use <code>LAYOFF</code> and pick a representative object for each layer. It is faster than hunting for layer names in the list. To bring them back, type <code>LAYON</code>.'),
      h3('Bản vẽ lớn, chạy chậm', 'Large drawing that feels slow'),
      p('Cân nhắc <code>LAYFRZ</code> cho các layer không cần xem lúc đó. Xem thêm các cách làm nhẹ bản vẽ ở bài <a href="/autocad/chiase/giam-dung-luong-file-dwg-autocad.html">giảm dung lượng file DWG</a>.',
        'Consider <code>LAYFRZ</code> for layers you do not need to see right now. For more ways to lighten a drawing, see the guide to <a href="/autocad/chiase/giam-dung-luong-file-dwg-autocad.html">reducing DWG size</a>.'),
      h3('Muốn giữ nền tham chiếu, tránh sửa nhầm', 'You want a reference backdrop that cannot be edited'),
      p('Dùng <code>LAYLCK</code> cho các layer nền (kiến trúc, lưới trục...). Muốn mở khóa một layer, dùng <code>LAYULK</code> rồi chọn đối tượng thuộc layer đó.',
        'Use <code>LAYLCK</code> on backdrop layers (architecture, grids...). To unlock one, run <code>LAYULK</code> and pick an object on that layer.'),
      h3('Muốn xem từng layer chứa gì', 'You want to see what each layer contains'),
      p('Dùng <code>LAYWALK</code>: chọn layer trong hộp thoại thì chỉ layer đó hiện. Rất tiện khi nhận bản vẽ của người khác mà chưa biết cấu trúc layer.',
        'Use <code>LAYWALK</code>: select a layer in the dialog and only that layer is shown. Very handy when you receive someone else\'s drawing and do not know its layer structure yet.'),

      h2('Điều chỉnh độ mờ khi khóa và làm mờ', 'Adjusting the fade amount'),
      p('Mức mờ của layer bị khóa do biến hệ thống <code>LAYLOCKFADECTL</code> điều khiển. Gõ tên biến để xem và đổi giá trị theo ý muốn. Cách chọn chế độ Tắt hoặc Khóa và làm mờ cho LAYISO được hướng dẫn trong <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">bài LAYISO</a>.',
        'The fade level of locked layers is controlled by the <code>LAYLOCKFADECTL</code> system variable. Type the variable name to view and change it. How to choose between Off and Lock-and-Fade for LAYISO is covered in the <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">LAYISO guide</a>.'),

      tip(['Muốn gõ ít hơn nữa?', 'Want to type even less?'],
          ['Bộ <a href="/autocad/autolisp/autolisp-layiso-layer-manager.html">Layiso Suite</a> của iViDLab gom các thao tác quản lý layer thành những phím tắt ngắn. Cách nạp Lisp xem tại <a href="/autocad/chiase/huong-dan-appload-lisp-autocad.html">hướng dẫn APPLOAD</a>.',
           'iViDLab\'s <a href="/autocad/autolisp/autolisp-layiso-layer-manager.html">Layiso Suite</a> packs layer management into short shortcuts. To load Lisp files, see the <a href="/autocad/chiase/huong-dan-appload-lisp-autocad.html">APPLOAD guide</a>.']),
    ],
  },

  {
    slug: 'huong-dan-lenh-laywalk-autocad',
    title: 'Hướng Dẫn Lệnh LAYWALK Trong AutoCAD: Duyệt Từng Layer Để Kiểm Tra Bản Vẽ',
    titleEn: 'LAYWALK in AutoCAD: Walk Through Layers to Audit a Drawing',
    badge: 'Hướng Dẫn Lệnh', badgeEn: 'Command Guide',
    desc: 'Cách dùng lệnh LAYWALK để xem từng layer riêng lẻ, tìm đối tượng lạ, kiểm tra bản vẽ nhận từ người khác và dọn layer thừa. Có mẹo khôi phục khi layer bị tắt nhầm.',
    descEn: 'How to use LAYWALK to view layers one at a time, find stray objects, audit a drawing from someone else and clean up unused layers, with tips for recovering layers left off by mistake.',
    related: ['phan-biet-layiso-layoff-layfrz-laylck-autocad', 'huong-dan-lenh-layiso-autocad', 'giam-dung-luong-file-dwg-autocad'],
    body: [
      p('Nhận một bản vẽ có hàng chục, thậm chí hàng trăm layer, bạn thường chẳng biết layer nào chứa gì. Mở bảng Layer rồi bật tắt từng cái rất mất thời gian. <code>LAYWALK</code> giải quyết việc này: nó cho bạn "đi dạo" qua từng layer, chọn layer nào thì bản vẽ chỉ hiện layer đó.',
        'When you receive a drawing with dozens or even hundreds of layers, you rarely know what each one holds, and toggling layers one by one in the Layer palette is slow. <code>LAYWALK</code> lets you "walk" through the layers: select a layer and the drawing shows only that layer.'),

      h2('Cách dùng LAYWALK cơ bản', 'Basic use of LAYWALK'),
      ul(['Gõ <code>LAYWALK</code> và nhấn Enter để mở hộp thoại Layer Walk.',
          'Hộp thoại liệt kê các layer trong bản vẽ. Bấm vào một layer thì chỉ layer đó hiển thị trên màn hình.',
          'Giữ <code>Ctrl</code> hoặc <code>Shift</code> để chọn nhiều layer cùng lúc và xem chúng cùng nhau.',
          'Nút <strong>Select Objects</strong> cho phép bạn chọn đối tượng ngay trên bản vẽ, hộp thoại sẽ chọn các layer chứa đối tượng đó. Rất tiện để tìm "đối tượng này nằm ở layer nào".',
          'Xong việc, đóng hộp thoại để trở về trạng thái layer ban đầu (nếu ô <strong>Restore on exit</strong> được tích).'],
         ['Type <code>LAYWALK</code> and press Enter to open the Layer Walk dialog.',
          'The dialog lists the layers in the drawing. Click a layer and only that layer is displayed.',
          'Hold <code>Ctrl</code> or <code>Shift</code> to select several layers and view them together.',
          'The <strong>Select Objects</strong> button lets you pick objects in the drawing and the dialog selects the layers that contain them. Handy for answering "which layer is this object on?".',
          'When finished, close the dialog to return to the original layer state (if <strong>Restore on exit</strong> is ticked).']),
      tip(['Luôn kiểm tra ô Restore on exit', 'Always check Restore on exit'],
          ['Khi duyệt, LAYWALK tạm thời thay đổi trạng thái hiển thị của layer. Giữ ô <strong>Restore on exit</strong> được tích để AutoCAD trả mọi thứ về như cũ khi bạn đóng hộp thoại.',
           'While walking, LAYWALK temporarily changes layer visibility. Keep <strong>Restore on exit</strong> ticked so AutoCAD puts everything back when you close the dialog.']),

      h2('Những việc LAYWALK làm rất tốt', 'What LAYWALK does best'),
      h3('1. Khám phá bản vẽ nhận từ người khác', '1. Explore a drawing from someone else'),
      p('Duyệt lần lượt các layer để biết cấu trúc: layer nào là trục, kích thước, ghi chú, kết cấu... Từ đó bạn dễ quyết định layer nào cần ẩn, khóa hay giữ lại.',
        'Step through the layers to learn the structure: which are grids, dimensions, notes, structure and so on. You can then decide which to hide, lock or keep.'),
      h3('2. Tìm đối tượng lạ hoặc nằm sai layer', '2. Find stray objects or objects on the wrong layer'),
      p('Thấy một đường line hay text không rõ nguồn gốc? Dùng <strong>Select Objects</strong> để biết nó thuộc layer nào, rồi xem layer đó còn chứa những gì khác. Rất hữu ích khi chuẩn hóa bản vẽ theo tiêu chuẩn layer của công ty.',
        'See a mystery line or text? Use <strong>Select Objects</strong> to learn its layer, then see what else is on that layer. Very useful when cleaning a drawing to match a company layer standard.'),
      h3('3. Tìm layer trống để dọn', '3. Spot empty layers to clean up'),
      p('Layer nào khi chọn mà màn hình không hiện gì thường là layer trống hoặc chỉ chứa đối tượng ngoài vùng nhìn. Kết hợp với <code>PURGE</code> để xóa layer không dùng. Xem thêm quy trình dọn bản vẽ ở bài <a href="/autocad/chiase/giam-dung-luong-file-dwg-autocad.html">giảm dung lượng file DWG</a>.',
        'A layer that shows nothing when selected is usually empty or holds objects outside the current view. Combine this with <code>PURGE</code> to remove unused layers. See the cleanup routine in the guide to <a href="/autocad/chiase/giam-dung-luong-file-dwg-autocad.html">reducing DWG size</a>.'),

      h2('LAYWALK khác LAYISO ở điểm nào?', 'How is LAYWALK different from LAYISO?'),
      ul(['<strong>LAYISO</strong>: bạn chọn <em>đối tượng</em> trên bản vẽ, các layer khác bị tắt hoặc khóa và làm mờ. Hợp để tập trung làm việc trên một nhóm đối tượng.',
          '<strong>LAYWALK</strong>: bạn chọn <em>layer</em> trong danh sách và xem trực tiếp kết quả. Hợp để khám phá và kiểm tra.'],
         ['<strong>LAYISO</strong>: you pick <em>objects</em> in the drawing and other layers are turned off or locked and faded. Best for focusing on a group of objects.',
          '<strong>LAYWALK</strong>: you pick <em>layers</em> from a list and see the result live. Best for exploring and auditing.']),
      p('So sánh đầy đủ các lệnh quản lý layer ở bài <a href="/autocad/chiase/phan-biet-layiso-layoff-layfrz-laylck-autocad.html">phân biệt LAYISO, LAYOFF, LAYFRZ, LAYLCK, LAYWALK</a>, và cách dùng chi tiết LAYISO ở <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">hướng dẫn LAYISO</a>.',
        'For a full comparison of the layer commands see <a href="/autocad/chiase/phan-biet-layiso-layoff-layfrz-laylck-autocad.html">LAYISO vs LAYOFF, LAYFRZ, LAYLCK and LAYWALK</a>, and for LAYISO in detail see the <a href="/autocad/chiase/huong-dan-lenh-layiso-autocad.html">LAYISO guide</a>.'),

      h2('Nếu layer bị tắt nhầm sau khi dùng', 'If layers are left off after using it'),
      ul(['Dùng <code>LAYERP</code> (Layer Previous) để quay về trạng thái layer trước đó.',
          'Gõ <code>LAYON</code> để bật lại tất cả layer đang tắt, và <code>LAYTHW</code> để rã băng tất cả layer đang đóng băng.',
          'Với bản vẽ hay phải kiểm tra, lưu trước một trạng thái layer bằng <code>LAS</code> (Layer States Manager) để khôi phục chỉ bằng một cú bấm.'],
         ['Use <code>LAYERP</code> (Layer Previous) to return to the previous layer state.',
          'Type <code>LAYON</code> to turn all layers back on and <code>LAYTHW</code> to thaw every frozen layer.',
          'For drawings you audit often, save a layer state first with <code>LAS</code> (Layer States Manager) so you can restore it in one click.']),

      tip(['Lưu ý về phiên bản', 'A note on versions'],
          ['Lệnh này nằm trong nhóm công cụ Layer Tools. Tùy bản AutoCAD và việc cài đặt Express Tools mà bạn có thể không thấy nó, nhất là trên AutoCAD LT. Nếu gõ lệnh báo <code>Unknown command</code>, hãy kiểm tra Express Tools đã được cài chưa.',
           'This command belongs to the Layer Tools group. Depending on your AutoCAD version and whether Express Tools is installed you may not see it, especially on AutoCAD LT. If it reports <code>Unknown command</code>, check that Express Tools is installed.']),
    ],
  },
];
